version: "3"
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "zz000:zz000"
  nginx:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - nodeserver
    ports:
      - "80:80"
