// permissions.ts

export enum Permission {
  GET_PERMISSIONS = "get_permissions",
  DELETE_ORGANIZATION = "delete_organization",
  DELETE_ACCOUNT = "delete_account",
  ADD_PERMISSION = "add_permission",
  REMOVE_PERMISSION = "remove_permission",
  // Existing permissions
  CREATE_ORGANIZATION = "create_organization",
  VIEW_ORGANIZATION = "view_organization",
  EDIT_ORGANIZATION = "edit_organization",
  ADD_STAFF = "add_staff",
  REMOVE_STAFF = "remove_staff",
  VIEW_STAFF = "view_staff",
  EDIT_STAFF_ROLE = "edit_staff_role",
  VIEW_CLIENTS = "view_clients",
  CREATE_TIMESHEETS = "create_timesheets",
  APPROVE_TIMESHEETS = "approve_timesheets",
  REJECT_TIMESHEETS = "reject_timesheets",
  DELETE_TIMESHEETS = "delete_timesheets",
  VIEW_TIMESHEETS = "view_timesheets",
  EDIT_TIMESHEETS = "edit_timesheets",
  VIEW_HOMES = "view_homes",
  EDIT_HOMES = "edit_homes",
  VIEW_AGENCIES = "view_agencies",
  EDIT_AGENCIES = "edit_agencies",
  VIEW_CHAT = "view_chat",
  EDIT_CHAT = "edit_chat",
  VIEW_INVOICES = "view_invoices",
  EDIT_INVOICES = "edit_invoices",
  VIEW_PAYMENTS = "view_payments",
  EDIT_PAYMENTS = "edit_payments",
  VIEW_SETTINGS = "view_settings",
  EDIT_SETTINGS = "edit_settings",
  VIEW_DASHBOARD = "view_dashboard",
  EDIT_CLIENTS = "edit_clients",
  VIEW_SCHEDULES = "view_schedules",
  EDIT_SCHEDULES = "edit_schedules",
  LINK_ORGANIZATIONS = "link_organizations",
  MANAGE_PARENT_COMPANY = "manage_parent_company",
  CREATE_SHIFT_PATTERN = "create_shift_pattern",
  EDIT_SHIFT_PATTERN = "edit_shift_pattern",
  DELETE_SHIFT_PATTERN = "delete_shift_pattern",
  VIEW_SHIFT_PATTERN = "view_shift_pattern",
  CREATE_SHIFT = "create_shift",
  DELETE_SHIFT = "delete_shift",
  UPDATE_SHIFT = "update_shift",
  ASSIGN_USERS = "assign_users",
  VIEW_SHIFT = "view_shift",
  CREATE_RESIDENT_DATA = "create_resident_data",
  UPDATE_RESIDENT_DATA = "update_resident_data",
  DELETE_RESIDENT_DATA = "delete_resident_data",
  CREATE_ROUTINES = "create_routines",
  UPDATE_ROUTINES = "update_routines",
  DELETE_ROUTINES = "delete_routines",
  CREATE_TASKS = "create_tasks",
  UPDATE_TASKS = "update_tasks",
  DELETE_TASKS = "delete_tasks",
  VIEW_TASKS = "view_tasks",
  VIEW_ROUTINES = "view_routines",
  VIEW_HISTORICAL_TASKS = "view_historical_tasks",
  VIEW_TASKS_BY_DATE_RANGE = "view_tasks_by_date_range",
  VIEW_COMPLETION_RATE = "view_completion_rate",
  RESCHEDULE_TASKS = "reschedule_tasks",
  GENERATE_TASKS = "generate_tasks",
  MARK_OVERDUE_TASKS = "mark_overdue_tasks",
  COMPLETE_TASKS = "complete_tasks",
  VIEW_UPCOMING_TASKS = "view_upcoming_tasks",
  VIEW_PENDING_TASKS = "view_pending_tasks",
  VIEW_CARE_ROUTINES = "view_care_routines",
  CREATE_CARE_ROUTINES = "create_care_routines",
  UPDATE_CARE_ROUTINES = "update_care_routines",
  DELETE_CARE_ROUTINES = "delete_care_routines",
  ACCEPT_INVITATION = "accept_invitation",
  REJECT_INVITATION = "reject_invitation",
  VIEW_INVITATIONS = "view_invitations",
  EDIT_INVITATIONS = "edit_invitations",
  DELETE_INVITATIONS = "delete_invitations",
  CREATE_INVITATIONS = "create_invitations",
  VIEW_NOTIFICATIONS = "view_notifications",
  DELETE_NOTIFICATIONS = "delete_notifications",
  CREATE_NOTIFICATIONS = "create_notifications",
  EDIT_NOTIFICATIONS = "edit_notifications",
  VIEW_REPORTS = "view_reports",
  CREATE_REPORTS = "create_reports",
  EDIT_REPORTS = "edit_reports",
  DELETE_REPORTS = "delete_reports",
  VIEW_CARE_PLANS = "view_care_plans",
  CREATE_CARE_PLANS = "create_care_plans",
  UPDATE_CARE_PLANS = "update_care_plans",
  DELETE_CARE_PLANS = "delete_care_plans",
  VIEW_CARE_NOTES = "view_care_notes",
  CREATE_CARE_NOTES = "create_care_notes",
  UPDATE_CARE_NOTES = "update_care_notes",
  DELETE_CARE_NOTES = "delete_care_notes",
  VIEW_MEDICATIONS = "view_medications",
  CREATE_MEDICATIONS = "create_medications",
  UPDATE_MEDICATIONS = "update_medications",
  DELETE_MEDICATIONS = "delete_medications",
  VIEW_MEDICAL_RECORDS = "view_medical_records",
  CREATE_MEDICAL_RECORDS = "create_medical_records",
  UPDATE_MEDICAL_RECORDS = "update_medical_records",
  DELETE_MEDICAL_RECORDS = "delete_medical_records",
  VIEW_MEDICAL_CONDITIONS = "view_medical_conditions",
  CREATE_MEDICAL_CONDITIONS = "create_medical_conditions",
  UPDATE_MEDICAL_CONDITIONS = "update_medical_conditions",
  DELETE_MEDICAL_CONDITIONS = "delete_medical_conditions",
  VIEW_ALLERGIES = "view_allergies",
  CREATE_ALLERGIES = "create_allergies",
  UPDATE_ALLERGIES = "update_allergies",
  DELETE_ALLERGIES = "delete_allergies",
  VIEW_RESIDENTS = "view_residents",
  VIEW_TASK_HISTORY = "view_task_history",
  UPDATE_TASK_HISTORY = "update_task_history",

  // New permissions
  VIEW_PAYROLL = "view_payroll",
  PROCESS_PAYROLL = "process_payroll",
  VIEW_EMPLOYEE_RECORDS = "view_employee_records",
  EDIT_EMPLOYEE_RECORDS = "edit_employee_records",
  VIEW_FINANCIAL_REPORTS = "view_financial_reports",
  CREATE_FINANCIAL_REPORTS = "create_financial_reports",
  VIEW_TRAINING_RECORDS = "view_training_records",
  EDIT_TRAINING_RECORDS = "edit_training_records",
  SCHEDULE_TRAINING = "schedule_training",
  VIEW_AUDIT_LOGS = "view_audit_logs",
  PERFORM_AUDITS = "perform_audits",
  VIEW_INVENTORY = "view_inventory",
  MANAGE_INVENTORY = "manage_inventory",
  VIEW_SUPPLIER_CONTRACTS = "view_supplier_contracts",
  MANAGE_SUPPLIER_CONTRACTS = "manage_supplier_contracts",
  VIEW_QUALITY_METRICS = "view_quality_metrics",
  EDIT_QUALITY_METRICS = "edit_quality_metrics",
  VIEW_COMPLIANCE_REPORTS = "view_compliance_reports",
  MANAGE_COMPLIANCE = "manage_compliance",
  VIEW_INCIDENT_REPORTS = "view_incident_reports",
  CREATE_INCIDENT_REPORTS = "create_incident_reports",
  MANAGE_INCIDENT_REPORTS = "manage_incident_reports",
}

export const RolePermissions = {
  owner: Object.values(Permission),
  admin: Object.values(Permission),
  manager: [
    Permission.VIEW_ORGANIZATION,
    Permission.VIEW_STAFF,
    Permission.VIEW_CLIENTS,
    Permission.VIEW_RESIDENTS,
    Permission.EDIT_CLIENTS,
    Permission.VIEW_SCHEDULES,
    Permission.EDIT_SCHEDULES,
    Permission.VIEW_TIMESHEETS,
    Permission.APPROVE_TIMESHEETS,
    Permission.VIEW_REPORTS,
    Permission.CREATE_REPORTS,
    Permission.VIEW_CARE_PLANS,
    Permission.VIEW_CARE_NOTES,
    Permission.VIEW_MEDICATIONS,
    Permission.VIEW_MEDICAL_RECORDS,
    Permission.VIEW_MEDICAL_CONDITIONS,
    Permission.VIEW_ALLERGIES,
    Permission.VIEW_QUALITY_METRICS,
    Permission.VIEW_INCIDENT_REPORTS,
    Permission.CREATE_INCIDENT_REPORTS,
  ],
  staff: [
    Permission.VIEW_ORGANIZATION,
    Permission.VIEW_CLIENTS,
    Permission.VIEW_RESIDENTS,
    Permission.VIEW_SCHEDULES,
    Permission.VIEW_CARE_PLANS,
    Permission.VIEW_CARE_NOTES,
    Permission.CREATE_CARE_NOTES,
    Permission.VIEW_MEDICATIONS,
    Permission.VIEW_MEDICAL_CONDITIONS,
    Permission.VIEW_ALLERGIES,
    Permission.CREATE_INCIDENT_REPORTS,
  ],
  carer: [
    Permission.VIEW_CLIENTS,
    Permission.VIEW_RESIDENTS,
    Permission.VIEW_SCHEDULES,
    Permission.VIEW_TIMESHEETS,
    Permission.CREATE_TIMESHEETS,
    Permission.VIEW_CHAT,
    Permission.VIEW_AGENCIES,
    Permission.VIEW_SETTINGS,
    Permission.VIEW_DASHBOARD,
    Permission.VIEW_CARE_PLANS,
    Permission.VIEW_CARE_NOTES,
    Permission.CREATE_CARE_NOTES,
    Permission.VIEW_MEDICATIONS,
    Permission.VIEW_MEDICAL_CONDITIONS,
    Permission.VIEW_ALLERGIES,
    Permission.COMPLETE_TASKS,
    Permission.VIEW_UPCOMING_TASKS,
    Permission.VIEW_PENDING_TASKS,
    Permission.CREATE_INCIDENT_REPORTS,
  ],
  nurse: [
    Permission.VIEW_CLIENTS,
    Permission.VIEW_RESIDENTS,
    Permission.VIEW_SCHEDULES,
    Permission.EDIT_SCHEDULES,
    Permission.VIEW_CARE_PLANS,
    Permission.CREATE_CARE_PLANS,
    Permission.UPDATE_CARE_PLANS,
    Permission.VIEW_CARE_NOTES,
    Permission.CREATE_CARE_NOTES,
    Permission.UPDATE_CARE_NOTES,
    Permission.VIEW_MEDICATIONS,
    Permission.CREATE_MEDICATIONS,
    Permission.UPDATE_MEDICATIONS,
    Permission.VIEW_MEDICAL_RECORDS,
    Permission.CREATE_MEDICAL_RECORDS,
    Permission.UPDATE_MEDICAL_RECORDS,
    Permission.VIEW_MEDICAL_CONDITIONS,
    Permission.CREATE_MEDICAL_CONDITIONS,
    Permission.UPDATE_MEDICAL_CONDITIONS,
    Permission.VIEW_ALLERGIES,
    Permission.CREATE_ALLERGIES,
    Permission.UPDATE_ALLERGIES,
    Permission.CREATE_INCIDENT_REPORTS,
  ],
  hr_manager: [
    Permission.VIEW_STAFF,
    Permission.EDIT_STAFF_ROLE,
    Permission.VIEW_EMPLOYEE_RECORDS,
    Permission.EDIT_EMPLOYEE_RECORDS,
    Permission.VIEW_TRAINING_RECORDS,
    Permission.EDIT_TRAINING_RECORDS,
    Permission.SCHEDULE_TRAINING,
    Permission.VIEW_PAYROLL,
    Permission.PROCESS_PAYROLL,
    Permission.VIEW_TIMESHEETS,
    Permission.APPROVE_TIMESHEETS,
    Permission.VIEW_REPORTS,
    Permission.CREATE_REPORTS,
    Permission.VIEW_INCIDENT_REPORTS,
    Permission.MANAGE_INCIDENT_REPORTS,
  ],
  accountant: [
    Permission.VIEW_INVOICES,
    Permission.EDIT_INVOICES,
    Permission.VIEW_PAYMENTS,
    Permission.EDIT_PAYMENTS,
    Permission.VIEW_PAYROLL,
    Permission.PROCESS_PAYROLL,
    Permission.VIEW_FINANCIAL_REPORTS,
    Permission.CREATE_FINANCIAL_REPORTS,
    Permission.VIEW_TIMESHEETS,
  ],
  admin_staff: [
    Permission.VIEW_ORGANIZATION,
    Permission.VIEW_STAFF,
    Permission.VIEW_CLIENTS,
    Permission.VIEW_RESIDENTS,
    Permission.VIEW_SCHEDULES,
    Permission.VIEW_TIMESHEETS,
    Permission.VIEW_HOMES,
    Permission.VIEW_AGENCIES,
    Permission.VIEW_CHAT,
    Permission.VIEW_INVOICES,
    Permission.VIEW_PAYMENTS,
    Permission.VIEW_SETTINGS,
    Permission.VIEW_DASHBOARD,
    Permission.VIEW_REPORTS,
    Permission.CREATE_REPORTS,
    Permission.VIEW_INVENTORY,
    Permission.MANAGE_INVENTORY,
  ],
  quality_assurance: [
    Permission.VIEW_CARE_PLANS,
    Permission.VIEW_CARE_NOTES,
    Permission.VIEW_MEDICAL_RECORDS,
    Permission.VIEW_QUALITY_METRICS,
    Permission.EDIT_QUALITY_METRICS,
    Permission.VIEW_COMPLIANCE_REPORTS,
    Permission.MANAGE_COMPLIANCE,
    Permission.PERFORM_AUDITS,
    Permission.VIEW_INCIDENT_REPORTS,
    Permission.MANAGE_INCIDENT_REPORTS,
  ],
  procurement_officer: [
    Permission.VIEW_INVENTORY,
    Permission.MANAGE_INVENTORY,
    Permission.VIEW_SUPPLIER_CONTRACTS,
    Permission.MANAGE_SUPPLIER_CONTRACTS,
  ],
};
